### ISSUE TITLE
about site.yml configurations

### ISSUE THREAD

**Issue by anxinyf** [lingxiankong/kubernetes-study#5]
in blob：https://lingxiankong.github.io/2018-02-23-openstack-k8s-integration.html, there're no descriptions of site.yml and /etc/ansible/hosts. 

And also, in site.yml, "subnet_id=$(openstack subnet list --network private -c ID -f value)" may be "subnet_id=$(openstack subnet list --name  private-subnet -c ID -f value)"???

In short， I failed to install k8s. most probably site.yml

**Comment by lingxiankong** [comment]
@anxinyf Hi, if you take a look at the readme file here https://github.com/lingxiankong/kubernetes-study/blob/HEAD/installation/ansible/version_3/README.md, you will see some commands changed.

Also, the ansible playbook works perfectly in my devstack environment, please provide more details of your failure if you need help.
