### ISSUE TITLE
Failed to provision volume with StorageClass "cinder-standard"

### ISSUE THREAD

**Issue by anxinyf** [lingxiankong/kubernetes-study#6]
error when creating PVC:  persistentvolume-controller  Failed to provision volume with StorageClass "cinder-standard": OpenStack cloud provider was not initialized properly : stat /etc/kubernetes/cloud-config: no such file or directory.

as your bolg did (https://lingxiankong.github.io/2018-02-23-openstack-k8s-integration.html#uayks).  i create SC and PV(also with lvmdriver-l type) , but encounter this issue, and find this http://eavesdrop.openstack.org/irclogs/%23openstack-containers/%23openstack-containers.2018-11-02.log.html.

I cannot understand about your solution:)

**Comment by anxinyf** [comment]
Thanks very much for your reply:)

in my all-in-one environment, using cloud-controller-manager, and i set up k8s cluster via kubeadm , just configure kubelet with --cloud-provider=external and --cloud-config. resources like pod, node, pv can be created, but not pvc.
And cinder service is ok, 
i don't know what happened:), may be i should try to set up cluster via cloud-provider-openstack

**Comment by lingxiankong** [comment]
To make PVC work with openstack-cloud-controller-manager, you need to tweak the controller-manager's configuration as I wrote [here](https://github.com/lingxiankong/kubernetes-study/blob/c90012d3549b202ca65d376b4983d45e1094d0ef/installation/ansible/external-cloud-provider/roles/kube_master/templates/kubeadm.conf.j2#L13).

**Comment by anxinyf** [comment]
ok, i'll try this! Thanks again：）
